### ISSUE TITLE
heroku Installation error

### ISSUE THREAD

**Issue by 44-83** [a092devs/fmheroku#1]
Execution git push heroku HEAD:master --force  An error occurred

remote: Step 9/14 : RUN git clone https://github.com/a092devs/fmheroku.git /bot
remote:  ---> Running in 096536dd6c57
remote: Cloning into '/bot'...
remote: Removing intermediate container 096536dd6c57
remote:  ---> d148e8577915
remote: Step 10/14 : COPY ./src/.constants.js /bot/src/
remote:  ---> 6ab479f9a87c
remote: Step 11/14 : COPY ./aria.sh ./client_secret.json ./credentials.json ./start.sh /bot/
remote:  ---> 8e31feb9aee3
remote: Step 12/14 : RUN cd /bot
remote:  ---> Running in 145ba2e5e6b6
remote: Removing intermediate container 145ba2e5e6b6
remote:  ---> 14d1c3baa58c
remote: Step 13/14 : RUN npm install && tsc
remote:  ---> Running in 50de74634522
remote: npm notice created a lockfile as package-lock.json. You should commit this file.
remote: npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
remote: npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
remote: npm WARN mirror-bot@2.0.0 No repository field.
remote: 
remote: added 266 packages from 315 contributors and audited 529 packages in 10.732s

**Comment by A-LoneWolf** [comment]
You didn't install @typescript-eslint/eslint-plugin@1.13.0 and  @typescript-eslint/parser@1.13.0 install it using
" npm i eslint@^5.0.0 "
Then "npm install"

**Comment by a092devs** [comment]
> Execution git push heroku HEAD:master --force An error occurred
> 
> remote: Step 9/14 : RUN git clone https://github.com/a092devs/fmheroku.git /bot
> remote: ---> Running in 096536dd6c57
> remote: Cloning into '/bot'...
> remote: Removing intermediate container 096536dd6c57
> remote: ---> d148e8577915
> remote: Step 10/14 : COPY ./src/.constants.js /bot/src/
> remote: ---> 6ab479f9a87c
> remote: Step 11/14 : COPY ./aria.sh ./client_secret.json ./credentials.json ./start.sh /bot/
> remote: ---> 8e31feb9aee3
> remote: Step 12/14 : RUN cd /bot
> remote: ---> Running in 145ba2e5e6b6
> remote: Removing intermediate container 145ba2e5e6b6
> remote: ---> 14d1c3baa58c
> remote: Step 13/14 : RUN npm install && tsc
> remote: ---> Running in 50de74634522
> remote: npm notice created a lockfile as package-lock.json. You should commit this file.
> remote: npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
> remote: npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
> remote: npm WARN mirror-bot@2.0.0 No repository field.
> remote:
> remote: added 266 packages from 315 contributors and audited 529 packages in 10.732s
